[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.0" # Ruff version.
hooks = [
  # Run the linter.
  { id = "ruff-check", types_or = ["python", "pyi", "pyproject"] },

  # Run the formatter.
  { id = "ruff-format", types_or = ["python", "pyi"] },
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "pyright",
    name = "pyright",
    entry = "uv run pyright",
    language = "system",
    pass_filenames = false,
    types_or = ["python", "pyi", "pyproject"]
  },
]