# This file was generated by generate_colour_stub.py
# DO NOT EDIT THIS FILE!

# Run: uv run generate-stubs

from enum import Enum
from typing import Any, ClassVar

class ColourEnum(Enum):
    RED: str
    GREEN: str
    YELLOW: str
    BLUE: str
    MAGENTA: str
    CYAN: str
    WHITE: str

class ColouredMeta(type):
    def __new__(
        mcs,
        name: str,
        bases: tuple[type, ...],
        namespace: dict[str, Any],
    ) -> type: ...

class Coloured(metaclass=ColouredMeta):
    RESET: ClassVar[str]
    colour_code: str

    def __init__(self, colour_code: str) -> None: ...
    def __call__(self, text: str) -> str: ...
    @classmethod
    def RED(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...
    @classmethod
    def GREEN(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...
    @classmethod
    def YELLOW(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...
    @classmethod
    def BLUE(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...
    @classmethod
    def MAGENTA(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...
    @classmethod
    def CYAN(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...
    @classmethod
    def WHITE(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...
    @classmethod
    def for_level(
        cls, text: str, level: str | int, *, bold: bool = False, reverse: bool = False
    ) -> str: ...
    @classmethod
    def _format(
        cls, text: str, code: str, bold: bool = False, reverse: bool = False
    ) -> str: ...
