from __future__ import annotations

import textwrap
from pathlib import Path

from tui_log_viewer.utils.colour import ColourEnum

OUTPUT_PATH = Path(__file__).parent.parent / "utils" / "colour.pyi"


def generate_colour_methods() -> str:
    methods: list[str] = []
    for colour in ColourEnum:
        methods.append(f"""
    @classmethod
    def {colour.name}(cls, text: str, bold: bool = False, reverse: bool = False) -> str: ...""")
    return "\n".join(methods)


def generate_stub() -> str:
    colour_members = "\n".join(f"    {colour.name}: str" for colour in ColourEnum)
    colour_members = "class ColourEnum(Enum):\n" + colour_members + "\n"

    header = textwrap.dedent("""\
    # This file was generated by generate_colour_stub.py
    # DO NOT EDIT THIS FILE!
    
    # Run: uv run generate-stubs
    
    from enum import Enum
    from typing import Any, ClassVar
    
    """)

    coloured_meta = """
class ColouredMeta(type):
    def __new__(
        mcs,
        name: str,
        bases: tuple[type, ...],
        namespace: dict[str, Any],
    ) -> type: ...
    """

    coloured = f"""
class Coloured(metaclass=ColouredMeta):
    RESET: ClassVar[str]
    colour_code: str

    def __init__(self, colour_code: str) -> None: ...

    def __call__(self, text: str) -> str: ...
    {generate_colour_methods()}
    
    @classmethod
    def for_level(cls, text: str, level: str | int, *, bold: bool = False, reverse: bool = False) -> str: ...
    
    @classmethod
    def _format(cls, text: str, code: str, bold: bool = False, reverse: bool = False) -> str: ...
"""

    return header + colour_members + coloured_meta + coloured


def generate() -> None:
    content = generate_stub()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated: {OUTPUT_PATH}")


if __name__ == "__main__":
    generate()
